name: Compile Examples

# The workflow will run on every push and pull request to the repository
on:
  - push
  - pull_request

jobs:
  compile-sketch:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        # pick some popular boards to run tests on
        fqbn:
          - arduino:avr:uno
          - arduino:avr:nano
          - arduino:megaavr:nona4809
          - arduino:avr:leonardo
          - arduino:samd:nano_33_iot
          - arduino:mbed:nano33ble

    steps:
      # This step makes the contents of the repository available to the workflow
      - name: Checkout repository
        uses: actions/checkout@v2

      # For more information: https://github.com/arduino/compile-sketches#readme
      - name: Compile sketch
        uses: arduino/compile-sketches@v1
        with:
          fqbn: ${{ matrix.fqbn }}
          sketch-paths: |
            # Configure the action to search all folders under the root of the repository for sketches and compile them.
            # This is formatted as a YAML list, which makes it possible to have multiple sketch paths if needed.
            - ./
          libraries: |
            # Only this library is needed
            - source-path: ./
